#commande pour installer un serveur web nginx 
#mettre à jour  le cahche de paquets
sudo apt update -y
#installation  paquet nginx
sudo apt install nginx
#version nginx
sudo nginx -v
#pour vérifier qu'il est actif 
sudo systemctl status nginx
#pour lancer le serveur à chaque demarage de la vm 
sudo systemctl enable nginx
#pour acceder au serveur web depuis le navigateur 
http://ip_vm