#commande pour installer ufw sous debian 
sudo apt-get upgrade
sudo apt-get install ufw
#pour l'activer 
sudo ufw enable 
#vérifier qu'il est actif
sudo ufw status numbered

##pour connaitre la passerelle ou l'ip de la machine ou du réseau autorisé a acceder en ssh a la vm 
route -n get default #gateway
ipconfig getifaddr en0 #ip 

#la régle pour autoriser le SSH uniquement avec le VPN est 
sudo ufw allow from 217.128.86.46 to any port 22
#pour bloquer les connexion ssh en entrée 
sudo ufw default deny incoming
#pour autoriser toutes les connexions sortantes
sudo ufw default allow outgoing

#Pour supprimer une règle 
#on liste les règles
sudo ufw status numbered
#Ensuite pour suppimer la règle qu'on souhaite supprimer, il faut ajouter son ID a la fin de la commande 
sudo ufw delete <ID>

#pour tester on se deconnecte en SSH et on essaie de se connecter sans le VPN 
