# Si la vm ne possède pas le ssh
apt install openssh-server -y

#Démarrer et activer le service
systemctl start ssh
systemctl enable ssh

#Vérifier que SSH tourne
systemctl status ssh

#ssh test
#ping la vm via son ip
ping ip_machine "IP_MACHINE"

#commande pour se connecter à une vm en ssh via ip
ssh rafael@192.168.1.114
