#se connecter en root
su root
whoami

#exporter le path
export PATH=$PATH:/usr/sbin:/sbin
#rendre permanent
echo 'export PATH=$PATH:/usr/sbin:/sbin' >> /root/.bashrc
#recharger
source /root/.bashrc

#mise à jour

apt update
apt upgrade -y

#installer les paquet essentiel

apt install -y \
sudo \
curl \
wget \
vim \
nano \
net-tools \
iproute2 \
openssh-server \
ca-certificates \
gnupg \
lsb-release \
htop \
bash-completion

#Pour vérifier curl par exemple
curl --version

#ajouter l'utilisateur "rafael" au grp sudo 
usermod -aG sudo rafael

#pour vérifier 
groups rafael

##se déconnecter du ssh puis se reconnecter


#revenir en utilisateur normal
su rafael

#pour effacer
clear
 
## Pour mettre la vm en IP fixe voici le process 
#connaitre le réseau de la vm
ip a #pour voir l'ip 
ip route show #pour connaitre la passerelle et la route par défaut
cat /etc/resolv.conf #pour connaitre le DNS

#mettre la vm en ip fixe, 
sudo nano /etc/network/interfaces #configuration de la carte réseau 
#pour basculer en mode "adresse IP statique", il faut remplacer la valeur dhcp par static
#Ensuite, on déclare les différentes propriétés : adresse IP et le masque de sous-réseau, la passerelle par défaut, les serveurs DNS et le nom de domaine local (facultatif).
auto ens18
iface ens18 inet static
        address <address destiné à être fixe>
        netmask 255.255.255.0
        gateway <la passerelle>
        dns-nameservers <DNS>

#ensuite on redemarre le service lié a notre réseau puis l'activer sur notre carte réseau.
sudo systemctl restart networking.service ; sudo ifup ens18
#on  peut rebbot pour vérifier en plus, cela va nous déconnecter 
sudo reboot
ssh user@ip_address 
ip a #ip de la vm
ip route show #obtenir la route par défaut et donc la passerelle utilisée.
cat /etc/network/interfaces #Afficher la configuration DNS, et donc les DNS utilisés.